import createMiddleware from "next-intl/middleware";
import type { NextRequest } from "next/server";
import { routing } from "./i18n/routing";

const intlMiddleware = createMiddleware(routing);

// TEMPORARY EN GATE (see src/app/[locale]/page.tsx's own comment): the
// homepage's EN variant hardcoded-redirects to the IT root while its copy
// is still Italian-only. The hreflang signal search engines actually see
// is THIS middleware's own Link response header — generated by next-intl
// from the full routing.locales list for the current path, with no
// per-route override — not generateMetadata's alternates.languages, which
// this app never renders as HTML <link> tags at all. So the `en` entry is
// stripped here, after next-intl builds it, rather than dismantling
// next-intl's alternate-links feature site-wide (every other route keeps
// both locales' alternates untouched). Remove this block once real EN
// copy exists and the gate itself is lifted.
const EN_GATED_PATHNAMES = new Set(["/", "/en"]);

export default function proxy(request: NextRequest) {
  const response = intlMiddleware(request);

  // Hard rule: any *.vercel.app host is always noindex, regardless of
  // environment. This specifically catches the production deployment's
  // own auto-assigned vercel.app alias, which VERCEL_ENV alone can't
  // distinguish from the real custom domain (see src/sanity/metadata.ts).
  // Runs here (per-request, at the edge) rather than in generateMetadata
  // so it doesn't force pages to render dynamically.
  if (request.nextUrl.hostname.endsWith(".vercel.app")) {
    response.headers.set("X-Robots-Tag", "noindex, nofollow");
  }

  if (EN_GATED_PATHNAMES.has(request.nextUrl.pathname)) {
    const link = response.headers.get("link");
    if (link) {
      const withoutEn = link
        .split(", ")
        .filter((entry) => !entry.includes('hreflang="en"'))
        .join(", ");
      response.headers.set("link", withoutEn);
    }
  }

  return response;
}

export const config = {
  // Skip /studio (Sanity Studio), /api routes, /design-preview (a
  // standalone design artifact route living outside the [locale] segment
  // entirely — see src/app/design-preview/layout.tsx's own comment — so
  // it must never be rewritten/redirected as if it needed locale
  // handling), Next.js internals, and any request for a file with an
  // extension (static assets: favicon.ico, images, etc).
  matcher: ["/((?!api|studio|design-preview|_next|_vercel|.*\\..*).*)"],
};
